version: "3.8"
services:
  odoo:
    image: odoo:14.0
    platform: linux/x86_64 # Fix for M1 macs
    container_name: odoo-app
    ports:
      - 8069:8069
    volumes:
      - ./data/files/:/var/lib/odoo
    depends_on:
      - db

  db:
    image: postgres:13
    platform: linux/x86_64 # Fix for M1 macs
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data/db/:/var/lib/postgresql/odoo-data
